language: android
jdk:
- oraclejdk8
env:
  global:
  - ANDROID_API=28
  - EMULATOR_API=19
  - ANDROID_BUILD_TOOLS=28.0.3
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  #  - android-$EMULATOR_API
  - extra-android-m2repository
  - extra-google-m2repository
  #  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  #  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  licenses:
  - ".+"

script:
- chmod +x gradlew

notifications:
  email: false
  slack: progarkworkspace:lJ8ROk1HkSIZfuegeamJk3fe

before_install:
- yes | sdkmanager "platforms;android-$ANDROID_API"